"""them 2 bang

Revision ID: e0ca853fc1d6
Revises: b43263f86ee6
Create Date: 2026-08-31 15:56:42.624267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ca853fc1d6'
down_revision: Union[str, Sequence[str], None] = 'b43263f86ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_code_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'code', name='uq_item_code')
    )
    op.create_index(op.f('ix_item_code_counts_item_id'), 'item_code_counts', ['item_id'], unique=False)
    op.create_table('item_stats',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('total_valid_responses', sa.Integer(), nullable=False),
    sa.Column('norm_version', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_stats')
    op.drop_index(op.f('ix_item_code_counts_item_id'), table_name='item_code_counts')
    op.drop_table('item_code_counts')
    # ### end Alembic commands ###
